[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Function configuration
[functions]
  # Directory setting
  directory = "netlify/functions"
  
  # Use esbuild for faster bundling
  node_bundler = "esbuild"

# Function-specific configuration
[functions.analyze-roof]
  # Increase timeout for this specific function
  included_files = ["node_modules/**"]

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
